<?php

namespace AppBundle\Repository;

/**
 * LigneStationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LigneStationRepository extends \Doctrine\ORM\EntityRepository
{
}
